# Generated by Django 5.1 on 2024-08-21 12:14

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Сюда надо загрузить изображения для вашего баннера', upload_to='banner_images')),
                ('title', models.CharField(help_text='Сюда надо писать название вашего баннера', max_length=200)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего услуги', verbose_name='banner_description')),
                ('link', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Сюда надо писать название вашего услуги', max_length=300)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего услуги', verbose_name='service_description')),
                ('image', models.FileField(help_text='Сюда надо загрузить изображения для вашего услуги', upload_to='service_images')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='ServiceImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_images', to='services.servicemodel')),
            ],
        ),
    ]
