# Generated by Django 5.1 on 2024-08-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceimagesmodel',
            options={'verbose_name': 'Изображения банера', 'verbose_name_plural': 'Изображения баннеров'},
        ),
    ]
