# Generated by Django 5.1 on 2024-08-31 15:48

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceimagesmodel_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text='Сюда надо загрузить изображения для вашего баннера', upload_to='rec_images')),
                ('title', models.CharField(help_text='Сюда надо писать название вашего баннера', max_length=200)),
                ('descriptions', ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего услуги', verbose_name='banner_description')),
                ('link', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
        migrations.CreateModel(
            name='ResourceImagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='resource_images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_images', to='services.resourcemodel')),
            ],
            options={
                'verbose_name': 'Изображения банера',
                'verbose_name_plural': 'Изображения баннеров',
            },
        ),
    ]
