# Generated by Django 5.1 on 2024-08-31 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_resourcemodel_resourceimagesmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourceimagesmodel',
            options={'verbose_name': 'Изображения ресурса', 'verbose_name_plural': 'Изображения ресурсов'},
        ),
        migrations.AlterModelOptions(
            name='resourcemodel',
            options={'verbose_name': 'Ресурс', 'verbose_name_plural': 'Ресурсы'},
        ),
    ]
