# Generated by Django 5.1 on 2024-08-31 15:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_resourcemodel_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemodel',
            name='descriptions',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Сюда надо писать описания для вашего ресурса', verbose_name='banner_description'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='image',
            field=models.FileField(help_text='Сюда надо загрузить изображения для вашего ресурса', upload_to='rec_images'),
        ),
        migrations.AlterField(
            model_name='resourcemodel',
            name='title',
            field=models.CharField(help_text='Сюда надо писать название вашего ресурса', max_length=200),
        ),
    ]
